# msa-auth-jwt Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth-container
          image: everyday365/auth10:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080